Use relative url since GH Pages use subfolders
Error: Failed to load resource: the server responded with a status of 404 () https://notesh.github.io/src/index.js